(define (square n)
    (* n n)
)
(define (f n m r) 
    (cond ((and (<= n m) (<= n r)) (+ (square m) (square r)))
          ((and (<= r m) (<= r n)) (+ (square m) (square n)))
          (else (+ (square r) (square n)))
    )        
)